### ISSUE TITLE
Trezor Password Manager (trezor.js) license?

### ISSUE THREAD

**Issue by cr7pt0** [trezor/trezor.js#36]
Hi thanks for the great project! I was looking through the source of your password manager - https://chrome.google.com/webstore/detail/trezor-password-manager/imloifkgjagghnncjkhggdhalmcnfklk?hl=en
and noticed there is no license. The trezor.js included has multiple licenses including MIT and BSD. What license is the Trezor Password Manager released as? I am asking here because I couldn't find a Trezor Password Manager repo anywhere. Thanks!

**Comment by prusnak** [comment]
TPM is not yet released.

**Comment by cr7pt0** [comment]
@prusnak there are quite a few users of the public beta would you be able to disclose what the license will be when released? Thanks.

**Comment by k3a** [comment]
Thanks for making all this but Trezor passwords are currently no use for me. To use Trezor as a password manager (which would be nice), I would need it working on both Firefox and Chrome on desktop (either using extensions or as a standalone app auto-typing passwords like KeePassXC) and Android support. That's why I am sticking with KeePassXC for now. Maybe if the code is released, open and easy to understand, it would motivate people to develop their extensions/software with this functionality...

**Comment by prusnak** [comment]
trezor.js is currently GNU Lesser General Public License v3.0 as stated in COPYING file.

Password manager is not open sourced yet.

**Comment by prusnak** [comment]
TPM uses https://github.com/satoshilabs/slips/blob/master/slip-0016.md so anyone can implement compatible software using this specification.
