### ISSUE TITLE
node-hid upgrade for node v8 compatibility

### ISSUE THREAD

**Issue by jcalfee** [trezor/trezor.js#37]
Please consider an upgrading node-hid to v0.5.7

https://github.com/node-hid/node-hid/issues/213

**Comment by karel-3d** [comment]
I see you have this app. Nice!

https://www.npmjs.com/package/trez

What do you think, is it better to have 2 packages - one with node stuff, one with web-related stuff - or one with both?

It's a bit annoying to have two packages, but OTOH I don't want to force the node-hid stuff on people with just web apps

**Comment by jcalfee** [comment]
You might look into the package.json "browser" entry point in addition to the "main" entry point.  For example:

https://github.com/crypto-browserify/randombytes/blob/v2.0.5/package.json#L25

**Comment by jcalfee** [comment]
Using "browser" and "main" should work like this: While the npm install will install everything, packagers like webpack and browserify will follow the correct path and only package the dependencies for the target platform.

**Comment by karel-3d** [comment]
:+1: ok, I will do that

I didn't want people to needlessly pull in node dependencies even during npm install (and vice versa). But having two package.jsons makes everything too complex. So I will try browser for browser and main for node.

**Comment by karel-3d** [comment]
I will do that over the week + update the node-hid stuff

**Comment by karel-3d** [comment]
We had some internal discussion and we will cut the node-hid support in the end.

The main reason is - we are planning to change trezor firmware so it no longer uses HID, but instead uses WebUSB, for easier access in Chrome. Because of some libusb issues on windows, we cannot make it backwards compatible and keep the HID. (see the long discussion here - https://github.com/trezor/trezor-mcu/pull/260 )

We are now making an updated bridge (trezord) that can work with both the new FW, through libusb, and the current FW, through hidapi. ( https://github.com/jpochyla/trezord-go ) 

But we don't want to write the support for node to directly do both hidapi and libusb, since none of our projects currently use the direct node support internally.

So, I will cut the node-hid support entirely and stop building the trezor.js-node (and trezor-link-node) packages. You are free to fork the repo.

Oh, and the new bridge should correctly accept calls from node apps (and electron apps, unlike now), so trezor.js should *still* work in node.js with bridge, just not directly.
