### ISSUE TITLE
Flow vs Typescript

### ISSUE THREAD

**Issue by marpme** [trezor/trezor.js#92]
What about to switch to support typescript as it is more common in the Javascript space.
Just wanted to raise the discussion before, I maybe invest my time in create a typescript'ed version of this repo :)

**Comment by karel-3d** [comment]
when I decided on Flow years ago, it had around the same popularity as TypeScript and I like how you can slowly convert the JS files to Flow, and I liked it more in general. 

But it seems TypeScript really won the race :(

I am not rewriting it right now, since we have Flow all around stack, but it's not a bad idea in general

**Comment by marpme** [comment]
@karel-3d Yeah that's why I waited before adopting this kind of technology, but I also think that VSCode did a great job at promoting typescript at this point. 

If you never the less need help with typescript at some point, lemme know.

@szymonlesisz Well I think if this really that deprecated and shouldn't be used for newer applications, well then I would definitively suggest to add some kind of "deprecation badge" as I didn't notice it in any way that it's an outdated lib.
